POST http://localhost:8080/api/teachers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNzM2ODQwODg4LCJleHAiOjE3Mzk0MzI4ODh9.Sbfj2M7Y8uv4LXODXvFg7DflTOXcTmUcl7RucVxQDQI

{
    "data": 
        {
            "name": "Prawee Wongsa"
        }
}